sudo: false

language: node_js
node_js:
  - '10'
  - '11'
  - '12'
  - '13'

before_install:
  # Configure signed git commits from within Travis CI, see:
  # https://github.com/semantic-release/git/tree/905f113a577c55cd9bb0a37ea3504d9e8ee2dfa2#gpg-signature
  # Decrypt git_gpg_keys.asc.enc key into /tmp/git_gpg_keys.asc
  - openssl aes-256-cbc -K $encrypted_44fd1061a48b_key -iv $encrypted_44fd1061a48b_iv -in ./config/travis-ci/git_gpg_keys.asc.enc -out /tmp/git_gpg_keys.asc -d
  # Make sure only the current user can read the keys
  - chmod 600 /tmp/git_gpg_keys.asc
  # Import the gpg key
  - gpg --batch --yes --import /tmp/git_gpg_keys.asc
  # Create a script that pass the passphrase to the gpg CLI called by git
  - echo '/usr/bin/gpg --passphrase ${GPG_PASSPHRASE} --batch --no-tty "$@"' > /tmp/gpg-with-passphrase && chmod +x /tmp/gpg-with-passphrase
  # Configure git to use the script that passes the passphrase
  - git config gpg.program "/tmp/gpg-with-passphrase"
  # Configure git to sign the commits and tags
  - git config commit.gpgsign true
  # Configure git to use your GPG key
  - git config --global user.signingkey ${GPG_KEY_ID}
  # Tests fail if not on any branch, so move to master
  - git checkout master
install:
  - npm install
before_script:
  - npm run setup
script:
  - commitlint-travis
  - npm run test:jest

jobs:
  include:
    - stage: codecov
      node_js: lts/*
      script:
        - npm run test:cov

    - stage: update CHANGELOG.md
      if: type = pull_request
      node_js: lts/*
      script: npx semantic-release # runs with PR-specific config

    - stage: release
      node_js: lts/*
      script: ':' # noop, skips tests
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release # runs with release-specific config
        on:
          # Branch selection is managed by semantic-release in .releaserc.yml
          all_branches: true
          repo: JuroOravec/semantic-release-changelog-update

notifications:
  email:
    on_success: never

env:
  global:
    # GH_TOKEN - semantic-release/github
    - secure: iWCb6JGYcFBURt0lYnrQzjx9/Us+MnAGlhIxA9Qo16o2CSvt42dalXQvLpHIeGB/IcGFBKUL/nXqUbvWZXUXAXjY51REBl0ztYqi4rw8yrxpKmMBhKlwBWjYCHERdN8CC0EnELakZsDcOmOaC5lx9KkDiKAbtDKigYrdvq6F2ynpdhjxVyeTvCPkZRQVOh39hwEyL1nnlhMg6qIlf8hnGN0RdJ/bcHebeqajTOgw0pv1HfCKxgiB95Bld2ZkvE1+NbfIHg9vSv8yn6O27L2m1FxB+olf+12Otc7BIpqM09ydjmVr5n+Xo6BXiOiWDMSvk5xImcZZbgzOj4EzhTsA9MZ7kmi5ftYKGobJNm+9O7/cVP1S7o0JnB4aEbknuvN+99Cv+ekj80zZw8zSS/TBWGhdQirSMYIoaPuxU5COryD6IKQMYwogXay2SF1NJZPu/yDkanRKcr1wiVwGG2uFxWZMRQWpxkkFznam7RmcWPndFpxXBAC+FMqs4W1cndPeBudf8h9/n64COigfnNbhdCLShQXMFc/l32ZKYN71H6xhiLmcmh98ErFUuo/Dd+0WFT5LHZghXZ1RrrUtwvG/suyiTm40P2mv0DLt2WqhpyOhWif8ij/jjnYXx+a3MZ8deLDvT+1z8/IJPoSQWwogRlNMgto+Go6vXEEi2Vh4i5o=
    # NPM_TOKEN - semantic-release/npm
    - secure: bnc/rVJZwLJ4bvWjvmdkqwjV2nI7sVGM2JVtCwTCscm/VhQcmnCR1mhUo1H7KQdUbH+y2x2frFNFsXkl2354Q+82OoWfLGWUQ8SeLT7yzHAa51M46pVOPibku2/VOdckohnDNpVfMOKdpDHwuMXQSWEJ0f1h6+BHlyn3gPT515rwTe2UHK8U3kAbWHoJXiY8DoRKi80b7DINFLav7n3J7X4LlCYRVg8yDJbUAll+Gb5nHa8qhT4HFxG/rt4wHj5YwYCKWgLD+KzXTjLWBD7fgNO5KcU8El7DjDA9STf6u4A5kJZkY5GdKa2A4xcAYMtyD0AiLFmA9dTOsHXNXt+yF0FvmHljztlFnPuIV41ZRmQaBB5GR9XLyoZcL+JRxH9tuJgEEts1gI7IpL1B5cOCgXaZUBX3pkyjB++VL5sncQhiavQ1QNrvNlVdPloyhCOtWGzHeEJhPjAvtj/hKyiPoAM+GXF3oCcs3GIQ7drKHOAbFH3QqXYfGe1xUoVE/L3Ty8ttyJND1V4rOw+v6KwweYuDdrgJmCqlYkTBs8c5zz1h+iDhjRKR7meeNHtBqVmYnqh2ph5j390/B33/mnlwfb868dvkbklgf6spZrFyvG75XveXETNB5oK2Lx+hCELZauaZiocme373gp7zLocY8sZMjXScel25xLEC97vupvE=
    # GPG signature env vars
    # https://github.com/semantic-release/git/tree/905f113a577c55cd9bb0a37ea3504d9e8ee2dfa2#gpg-signature
    # GPG_PASSPHRASE
    - secure: AE0gqGf4hsoK7jnwOrZD0VVl906AOby4c0MLx1HE8SvwkaeOSgIVf+H0L38bZNWV53bZw32j7OWGZ7aTQoP0LwSRoglBIAGQrIabTh2bdzeqSplMpxaMNcuiFPJjqu5x7LDWbDpZWxMMvi5fkjcTHYgmMkPl0NHk7Ax5svlB0l3lwo8Q3NGy4gzUbELX5CHNB3tPA4O9Kf+rIQ3SCAr0C0vliHTPkrjbjVZvrvPrG5tX62NjrK4IBuFOJakGP4GbcMM8q8S/Ok3jG4gHOcFwvPQcAlL22IDptLBxJCp1GNCzUT8heGRc1O6G8s82YooCUZLz/7wRGSjxG+HClt9eJturKCItRI1jLZQ+fMSg6lcBfasFILr5r5zQ1slNShsJ9mjZDh6fTMhQ7F5LqOzG7e0nMwh8lWikRz2boRSAH4v6TmXq51Q48mWqFNhotPWnHWO0ZwdcIIUtAdcaOqSE5AFDvFnLDDWn+32DBQqN4bIfuSGa0lSihdqIc5FWTAw3uS93adwDJ1AbkdDNILBz4QYFtNL9n4N42iW3qVsCME4WzO5Du/HRrIMZspLKEWlm2mADI9xEYtHErWlrx075eRnoBCNp80I5n0wehOyyHRjS5nv30czi4qwWNJo2im0YOOfHzAyM9Ln33IlfUNjmAJBk+P3KNsd+0M3WIHm3zSc=
    # GPG_KEY_ID
    - secure: nxemZZ1oy7Dds10bsSdRpE2OAnMLyaWsq3vJHvIahsWDHl79YKWpTiH4OKL1SrljCWbEokBOMBlTzqGGqLS38IC89AS41lLm92IiQn/Aqjbju4rQSwWFw0st/Ol43VqW9X/nB01sdE4LJ2EUw2oW6n1mq1yRghA5KCYMT62Det7TE/eXenb1shW9+VR5mh8q7T1pBTg0QZtcAOUGAma4y6hjKNscSJecEDT9HNBStexk63NdT7YK+/PTkxhgju3orO9e7zMtIz20kPOBcYAzLxmBhmmnslYXkBSlSpwyjdk8ceNky3hsx7K7gg0BY0NggJJgp+zM62r2HDbvYRvXBGbWdI1xfo5uZJ4VcXpctJ+oJYdXuBKCwLducvoJxIHP8GY48RQym5LKkCn1/YMOBVHNjdQkqyQ3jk2tH2OKIkCRqkSfFtznXrruyIHudcbF1Q+y8zLQyGO7TQht/2XFySAW3RWoUJ48t1AsqtufDFmNSIwK4VfWqPc2qKoYFKiD2iaUNFrpe43VG0oOuHKPuPX8IcKu/jw/AC0+zvxsqSPT9XtbndakaDegUnHHzdO6PWcGaa+4eEPDxvqNmtWdFwXo5OVuX1cZp8pUgiHMACT2jYPYrEZoDdoIwFzkNpCTFCaRqyISGODbxboWB2peZ/Z+h72kaOiCe+YRTULg+d4=
    # GIT_EMAIL
    - secure: N0lmXSUac1MOxQZn66v0CrPYthcojClqR/JMw3MlLX6YaA63OXjV5Pkyq1ZIKNQFsFU0d2uJLCmIBnhcNdPWWgNeM6hO2B8PpdARJKeWaXhypTXW7iUqm/Eb6BDQxip83Prp3XSTsyYFUs5iepEiW6/TJFnSxFKw+VWXxFpUtbcDY/diPQ6ZgoJQcbqTWSw79v8wnDEAT9+yLczf8GcLDPNu7GkYlwj88vZfTuOcSkgbl5ayOIhT6kr8W6Y2sRkBdgw9J03KpTf+jpmX4lU9k2pA7r3JJX2e8t0+GNoQGklTYFV6/I6346UVBRjgnLKaIMxwjXDERT3OF+mrfYVKugIxCBue6nPzyPd/qebIp7TtZTLNdmP8NqFj+xtCF5PRs+fmWXHmZwFWd8hnhyjlYQBq2Wj0kDcxL4CDT2n0NyTC0Lc6Pd/d6VoABYq9ZVWKI4SUXbp5QdAsJB08DXBJLI+y3ODeOqZ8rzG0yiQZQEt/SHvFNteuQnque8elt+l97jaGBSpwSE6xeOgU4hP2WGuN/7F8lUYS+IE/+PGBfHs9peRK65w7Q1QQcW5Ut7/3aEjgNYmJO3uv0+M3/VjYd6haX1a8izAkr4l93IZKzcICXLgHdQKx9Kac2JhUzHuJGc722cbdSyyNpzaKOjZZjneuq3GCOOOtg2etI9B6/3Y=
    # GIT_USERNAME
    - secure: ZXql/CKs7Gv42geAJj1pG/SwfDMIvPvTKSVhdTDu8xA2GCt4I74WPp01bHzYVh6b6NTrGk1T8M1PycOHR/CWGGXX8IisBAtfY+Qn6wH4t3PyrZTRSsRPp56Z2k8N/xm9pWLnpwl+2KA9X13Wj5MwdwixkwlKmR208eIHLl+amC/OkL693W4xkq4MDcTJJlGMXcTwgSnTGbDG4JhIfxQd9I032e3FowpH7IvufEhDQBNNH0ybdHqzTkYWvPwzfe7EWp20dKlnFdIpjBzPCAxglxPSZssw2mRDWu1e0oTxm6aLKwEXOGTrKxwwGqF+ffsvQvRejX24IrOp6V2FV+M2eOf279yHodzTRVn91nOW7jVxdvtejZ1Kin3RnlZLPD4+twTxPxjynjcYuPNDhsTGG5whK+AFT2MPt2PhsTDn5hAW91POTtK0PDSGMEvVjTGFh07dSKsSZ0q7+kS3mmD9N94P3qImvcpcCQf4QGEJOfWXcU995mtdelAv9MXN5hwTYp+ZFoDEgVTXWJBtRbOZ4SZBv4KLyG1xWyBgE1qHkR5/BWvnRyc+keBL0c6o8bAbTtlfp8/76LWO4xHDhxqh/yXHFjtXYBUblU/80a+vXOWtqNImrHBRHeZH2Q6EwppNe0mUmKoh+hrAHC6Ph1wXKPvSX/6SmbLntyMOyp4YcEk=
